services:
  bind-service:
    image: shirachech15751/bind-service:1.0.1
    container_name: bind-service
    networks:
      - app-net

  submission:
    image: shirachech15751/submission:1.0.0
    container_name: submission
    depends_on:
      - bind-service
    environment:
      BIND_SERVICE_BASE_URL: http://bind-service:8001
      FRONTEND_ORIGINS: http://localhost:3000
    ports:
      - "8000:8000"
    networks:
      - app-net

  submission-client:
    image: shirachech15751/submission-client:1.0.1
    container_name: submission-client
    depends_on:
      - submission
    ports:
      - "3000:3000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

